::==============================================================================
::  autogoto.bat
::==============================================================================
:::.{head}.Summary:
:::
:::  A script with multiple labeled sections. The first command-line argument
:::  selects a label to goto.
:::
:::  Labels may defined as:
:::
:::    :.autogoto.                Runs when no arguments are provided.
:::    :.autogoto.?               Runs when first argument is /?
:::    :.autogoto.[FLAG]          Runs when first argument is /[FLAG]
:::
:::  If the specified label does not exist, prints autogenerated usage info.
:::
::==============================================================================
@echo off & for /f "tokens=1-3 delims=/-" %%1 in (".autogoto./%1") do (if "%%3"=="" (shift /1&goto :%%1%%2) else goto) 2>nul || (%=Usage Info=% setlocal DisableDelayedExpansion&echo.&echo Usage:&echo.&(for /F "tokens=1* delims=:." %%A in ('findstr /RIC:"^:\.autogoto\.\ " "%~f0"') do echo   %~nx0  %%B)&(for /F "tokens=1* delims=:." %%A in ('findstr /RIC:"^:\.autogoto\.[^\ ]" "%~f0"') do echo   %~nx0 /%%B)&endlocal)



%====================================================================%  goto :EOF
:.autogoto.                  Description text
setlocal DisableDelayedExpansion
:: This code executed if script is run with no arguments.
:: Remove this section to prevent the script from running without arguments.
echo(No arguments provided.
exit /b 0
%==================  END .autogoto.  ================================%  goto :EOF



%====================================================================%  goto :EOF
:.autogoto.flag              Description text
setlocal DisableDelayedExpansion
:: This code executed if script is run with the first argument "/flag".
:: Args are already shifted; %1 is the first argument after "/flag", etc.
:: Unfortunately, "%*" is not affected by 'shift', so we must shift manually:
for /f "tokens=1*" %%a in (^"%*^") do set ^"args=%%b"
echo(Now in section: /flag
exit /b 0
%==================  END .autogoto.flag  ============================%  goto :EOF



%====================================================================%  goto :EOF
:.autogoto.? [keyword]       Prints detailed documentation.
setlocal DisableDelayedExpansion
if exist "%~dp0man.bat" (set "man=%~dp0man.bat") else for %%P in ("man.bat") do set "man=%%~$PATH:P"
if "%~1"=="" (
	call "%~f0" print/usage
	if defined man call "%man%" "%~f0" "/inc:{head}"
) else (
	if defined man call "%man%" "%~1 /exc:{head} /exc:.autogoto."
)
exit /b 1
%==================  END .autogoto.?  ===============================%  goto :EOF



%====================================================================%  goto :EOF
:function [args]
setlocal DisableDelayedExpansion
:: Labels which do not start with '.autogoto.' are not accessible
:: from the command line and are hidden from the autogenerated usage text.
exit /b 0
%==================  END function  ==================================%  goto :EOF
