::==============================================================================
::  autogoto_template.bat
::==============================================================================
:::.Summary:
:::
:::  Script framework which uses the first argument as the name of a label,
:::  and jumps to it.
:::
:::  If the label does not exist, prints autogenerated usage info.
:::  Correctly handles '/?' and '' (empty) first argument.
:::
::==============================================================================
@echo off & for /f "tokens=1-3 delims=/-" %%1 in (".autogoto./%1") do (if "%%3"=="" (goto :%%1%%2) else goto) 2>nul || (%=Usage Info=% setlocal DisableDelayedExpansion&echo.&echo Usage:&echo.&(for /F "tokens=1* delims=:." %%A in ('findstr /RIC:"^:\.autogoto\.\ " "%~f0"') do echo   %~nx0  %%B)&(for /F "tokens=1* delims=:." %%A in ('findstr /RIC:"^:\.autogoto\.[^\ ]" "%~f0"') do echo   %~nx0 /%%B)&endlocal)



%====================================================================%  goto :EOF
:.autogoto.                  Description text
setlocal DisableDelayedExpansion
:: This code executed if script is run with no arguments.
:: Remove this section to prevent the script from running without arguments.
echo No arguments provided
exit /b 0
%==================  END .autogoto.  ================================%  goto :EOF



%====================================================================%  goto :EOF
:.autogoto.flag              Description text
setlocal DisableDelayedExpansion
:: This code executed if script is run with the first argument "/flag".
echo Now in section: /flag
exit /b 0
%==================  END .autogoto.flag  ============================%  goto :EOF



%====================================================================%  goto :EOF
:.autogoto.? [keyword]       Prints detailed documentation.
setlocal DisableDelayedExpansion
if "%~2"=="" (
	call "%~f0" print/usage
	man.bat "%~f0" "Summary"
) else (
	man.bat "%~f0" "%~2 /exc:Summary /exc:.autogoto."
)
exit /b 1
%==================  END .autogoto.?  ===============================%  goto :EOF



%====================================================================%  goto :EOF
:function [args]
setlocal DisableDelayedExpansion
:: This is an internal label/function which is hidden from the help text.
exit /b 0
%==================  END function  ==================================%  goto :EOF
